# help(dash.dcc.Dropdown)
! pip install openpyxl wordcloud dash plotly pandas numpy jupyter-dash wordcloud dash-bootstrap-components matplotlib pillow

### Dash 
Link: https://dash.plotly.com/tutorial
To install: pip install dash
Can Run: app.py file in jupyter notebook

In [1]:
# import library
import pandas as pd
import numpy as np
import dash
import plotly.express as px
from jupyter_dash import JupyterDash
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go
from wordcloud import WordCloud
import io
import base64
import matplotlib.pyplot as plt
from collections import Counter
import dash_bootstrap_components as dbc
from io import BytesIO
from collections import Counter
from PIL import Image
from datetime import datetime, timedelta
import json

# Call data from Github
# path = "C:/Users/sokhe/OneDrive - Cambodia Academy of Digital Technology/Data_Science_CADT/1. Resume_Ranking_System_2023/2. work_in 2023/3. EDA/CamHr_Data__Pivot_table.xlsx"
path = "./CamHr_Data__Pivot_table.xlsx"
df = pd.read_excel(path)
print(df.shape)
df.info()

(26293, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26293 entries, 0 to 26292
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Position          26293 non-null  object
 1   Job_Title1        26293 non-null  object
 2   Job_Title2        882 non-null    object
 3   Job_Title3        43 non-null     object
 4   Job_Title4        10 non-null     object
 5   Job_Title5        1 non-null      object
 6   Position_Level    26293 non-null  object
 7   Year_Experience   26293 non-null  int64
 8   Hiring            26293 non-null  int64
 9   Salary            26293 non-null  object
 10  Gender            26293 non-null  object
 11  Age               26293 non-null  object
 12  Job_Type          26293 non-null  object
 13  Job_Category      26293 non-null  object
 14  Industry          26293 non-null  object
 15  Qualification     26293 non-null  object
 16  Language          26293 non-null  object
 17  Location          26293 non-null  object
 18  Job_Description   26293 non-null  object
 19  Job_Requirements  26259 non-null  object
 20  Publish_Date      26293 non-null  datetime64[ns]
 21  Closing_Date      26293 non-null  datetime64[ns]
 22  Average_Age       26293 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(2), object(18)
memory usage: 4.6+ MB

In [2]:
#Replace IT with Information Technology
df['Job_Category'] = df['Job_Category'].replace('IT', 'Information Technology')

In [3]:
df['Job_Title1'] = df['Job_Title1'].str.replace('  ', '')
df['Job_Title2'] = df['Job_Title2'].str.replace('  ', '')
df['Job_Title3'] = df['Job_Title3'].str.replace('  ', '')
df['Job_Title4'] = df['Job_Title4'].str.replace('  ', '')
df['Job_Title5'] = df['Job_Title5'].str.replace('  ', '')
# Trim Text
df['Job_Title1'].str.strip()
df['Job_Title2'].str.strip()
df['Job_Title3'].str.strip()
df['Job_Title4'].str.strip()
df['Job_Title5'].str.strip()

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
26288    NaN
26289    NaN
26290    NaN
26291    NaN
26292    NaN
Name: Job_Title5, Length: 26293, dtype: object

In [4]:
# merge job title
df['Job_Title'] = df[['Job_Title1', 'Job_Title2', 'Job_Title3', 'Job_Title4', 'Job_Title5']].apply(lambda x: ', '.join(x.dropna().astype(str)), axis=1)
# Remove white space
df['Job_Title'] = df['Job_Title'].str.replace('  ', '')
# Trim Text
df['Job_Title'].str.strip()
df

,Position,Job_Title1,Job_Title2,Job_Title3,Job_Title4,Job_Title5,Position_Level,Year_Experience,Hiring,Salary,...,Industry,Qualification,Language,Location,Job_Description,Job_Requirements,Publish_Date,Closing_Date,Average_Age,Job_Title
0,Poster Designer,Designer,NaN,NaN,NaN,NaN,Middle,1,1,$200-$500,...,Entertainment,No limitations,Japanese,Phnom Penh,Japnese language understanding. Video editing ...,Skill of japanese language want design sense w...,2023-01-16,2023-02-15,18.0,Designer
1,BOA-Registered Architect/ Senior Architect,BOA-Registered Architecture,Senior Architect,NaN,NaN,NaN,Senior,5,1,Negotiable,...,Architecture/Building/Construction,Bachelor's Degree,English,Phnom Penh,2 positions for cambodia boa registered archit...,Recognized degree and preferably registered wi...,2023-03-13,2023-03-23,18.0,"BOA-Registered Architecture, Senior Architect"
2,Interior Architect/ Intermediate Interior Desi...,Interior Architecture,Intermediate Interior Designer,Intermediate Project Coordinator,NaN,NaN,Senior,3,1,Negotiable,...,Architecture/Building/Construction,Bachelor's Degree,English,Phnom Penh,The company is seeking an experienced INTERIOR...,Minimum of 3 to 5 years experience in a simila...,2023-03-13,2023-03-23,18.0,"Interior Architecture, Intermediate Interior D..."
3,A/C Maintenance Team Leader,Air Conditioner Maintenance Team Leader,NaN,NaN,NaN,NaN,Others,2,1,Negotiable,...,Electronics/Electrical/Mechanical Equipment,No limitations,Others,Phnom Penh,None,None,2022-12-20,2023-01-19,18.0,Air Conditioner Maintenance Team Leader
4,A/R Supervisor,Accountant Receivable Supervisor,NaN,NaN,NaN,NaN,Senior,4,1,Negotiable,...,Trading,Bachelor's Degree,English,Phnom Penh,Issue invoices for goods and or services rende...,Financial management knowledge mathematical mi...,2023-03-21,2023-04-20,18.0,Accountant Receivable Supervisor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26288,Customer Relation Officer,Customer Relation Officer,NaN,NaN,NaN,NaN,Middle,2,20,Negotiable,...,Banking & Finance,Bachelor's Degree,English/Vietnamese,Phnom Penh/Siem Reap/Takhmao,Location ho branches in pp ta khmau siem reap ...,Ii. Education AND EXPERIENCE REQUIREMENT year ...,2023-06-01,2023-07-01,27.5,Customer Relation Officer
26289,Customer Service Officer,Customer Service,NaN,NaN,NaN,NaN,Middle,2,10,Negotiable,...,Banking & Finance,Bachelor's Degree,English/Vietnamese,Phnom Penh/Takhmao,Handle cash for all the transactions including...,Ii. Education AND EXPERIENCE REQUIREMENT year ...,2023-06-01,2023-07-01,27.5,Customer Service
26290,QC Operator,QC Operator,NaN,NaN,NaN,NaN,Fresh Graduate,1,4,Negotiable,...,Chemical/Plastic/Paper/Petrochemical,High School,English,Phnom Penh,Summary OF DUTY as a QC operator you are respo...,High school certificate or relevant certifica...,2023-06-01,2023-07-01,27.5,QC Operator
26291,Warehouse And Transportation Coordinator,Warehouse & Transportation Coordinator,NaN,NaN,NaN,NaN,Middle,1,1,Negotiable,...,Chemical/Plastic/Paper/Petrochemical,Bachelor's Degree,English,Phnom Penh,Understand and follow all transportation wareh...,Bachelor s degree or higher in related fields ...,2023-06-01,2023-07-01,18.0,Warehouse & Transportation Coordinator
26292,Inventory Operator,Inventory Operator,NaN,NaN,NaN,NaN,Middle,1,1,Negotiable,...,Chemical/Plastic/Paper/Petrochemical,High School,English,Phnom Penh,Summary OF DUTY as an inventory officer you ar...,High school certificate or relevant certificat...,2023-06-01,2023-07-01,27.5,Inventory Operator

In [2]:
df['Position'].value_counts()

Senior Officer                              345
Accountant                                  204
Sales Executive                             203
Sales Executive                             165
Accountant                                  154
                                           ...
Manager Country Finance (Cambodia)            1
Manager Services Delivery and Deployment      1
Manager Central Warehouse                     1
Manager Area Sales (Provinces)                1
Credit Senior Officer                         1
Name: Position, Length: 8073, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26293 entries, 0 to 26292
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Position          26293 non-null  object
 1   Job_Title1        26293 non-null  object
 2   Job_Title2        882 non-null    object
 3   Job_Title3        43 non-null     object
 4   Job_Title4        10 non-null     object
 5   Job_Title5        1 non-null      object
 6   Position_Level    26293 non-null  object
 7   Year_Experience   26293 non-null  int64
 8   Hiring            26293 non-null  int64
 9   Salary            26293 non-null  object
 10  Gender            26293 non-null  object
 11  Age               26293 non-null  object
 12  Job_Type          26293 non-null  object
 13  Job_Category      26293 non-null  object
 14  Industry          26293 non-null  object
 15  Qualification     26293 non-null  object
 16  Language          26293 non-null  object
 17  Location          26293 non-null  object
 18  Job_Description   26293 non-null  object
 19  Job_Requirements  26259 non-null  object
 20  Publish_Date      26293 non-null  datetime64[ns]
 21  Closing_Date      26293 non-null  datetime64[ns]
 22  Average_Age       26293 non-null  float64
 23  Job_Title         26293 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(19)
memory usage: 4.8+ MB

In [7]:
# Separate d/m/date/y from transaction date
df['MonthYear'] = df['Publish_Date'].dt.strftime('%b %Y')
df.head()

,Position,Job_Title1,Job_Title2,Job_Title3,Job_Title4,Job_Title5,Position_Level,Year_Experience,Hiring,Salary,...,Qualification,Language,Location,Job_Description,Job_Requirements,Publish_Date,Closing_Date,Average_Age,Job_Title,MonthYear
0,Poster Designer,Designer,NaN,NaN,NaN,NaN,Middle,1,1,$200-$500,...,No limitations,Japanese,Phnom Penh,Japnese language understanding. Video editing ...,Skill of japanese language want design sense w...,2023-01-16,2023-02-15,18.0,Designer,Jan 2023
1,BOA-Registered Architect/ Senior Architect,BOA-Registered Architecture,Senior Architect,NaN,NaN,NaN,Senior,5,1,Negotiable,...,Bachelor's Degree,English,Phnom Penh,2 positions for cambodia boa registered archit...,Recognized degree and preferably registered wi...,2023-03-13,2023-03-23,18.0,"BOA-Registered Architecture, Senior Architect",Mar 2023
2,Interior Architect/ Intermediate Interior Desi...,Interior Architecture,Intermediate Interior Designer,Intermediate Project Coordinator,NaN,NaN,Senior,3,1,Negotiable,...,Bachelor's Degree,English,Phnom Penh,The company is seeking an experienced INTERIOR...,Minimum of 3 to 5 years experience in a simila...,2023-03-13,2023-03-23,18.0,"Interior Architecture, Intermediate Interior D...",Mar 2023
3,A/C Maintenance Team Leader,Air Conditioner Maintenance Team Leader,NaN,NaN,NaN,NaN,Others,2,1,Negotiable,...,No limitations,Others,Phnom Penh,None,None,2022-12-20,2023-01-19,18.0,Air Conditioner Maintenance Team Leader,Dec 2022
4,A/R Supervisor,Accountant Receivable Supervisor,NaN,NaN,NaN,NaN,Senior,4,1,Negotiable,...,Bachelor's Degree,English,Phnom Penh,Issue invoices for goods and or services rende...,Financial management knowledge mathematical mi...,2023-03-21,2023-04-20,18.0,Accountant Receivable Supervisor,Mar 2023

In [8]:
df['MonthYear'] = df['MonthYear'].str.strip()

In [9]:
df.columns

Index(['Position', 'Job_Title1', 'Job_Title2', 'Job_Title3', 'Job_Title4',
       'Job_Title5', 'Position_Level', 'Year_Experience', 'Hiring', 'Salary',
       'Gender', 'Age', 'Job_Type', 'Job_Category', 'Industry',
       'Qualification', 'Language', 'Location', 'Job_Description',
       'Job_Requirements', 'Publish_Date', 'Closing_Date', 'Average_Age',
       'Job_Title', 'MonthYear'],
      dtype='object')

In [10]:
lag = df['Language'].value_counts()
lag

English                                        21638
Others                                          2195
Chinese-Mandarin/English                         901
English/Khmer                                    518
Chinese-Mandarin                                 263
Khmer                                            211
Japanese                                         122
English/Thai                                      65
English/Korean                                    57
Chinese-Mandarin/English/Khmer                    36
English/Japanese                                  31
Chinese-Cantonese/English                         29
English/English                                   28
French                                            27
English/Vietnamese                                24
Thai                                              23
Chinese-Cantonese/Chinese-Mandarin/English        21
Chinese-Mandarin/English/Korean                   19
Chinese-Mandarin/English/Thai                      9
Chinese-Mandarin/Khmer                             9
English/French                                     9
Chinese-Cantonese/Chinese-Mandarin/Japanese        9
English/French/Japanese                            8
English/English/Korean                             6
Chinese-Mandarin/English/Vietnamese                6
Korean                                             6
English/Khmer/Korean                               4
French/French                                      3
English/French/Khmer                               3
Khmer/Korean                                       2
Vietnamese                                         2
Chinese-Cantonese                                  2
Japanese/Korean                                    1
Chinese-Mandarin/Japanese/Korean                   1
Chinese-Cantonese/Chinese-Mandarin                 1
English/Japanese/Thai                              1
Chinese-Mandarin/Thai                              1
Chinese-Mandarin/Vietnamese                        1
Chinese-Mandarin/English/Japanese                  1
Name: Language, dtype: int64

In [11]:
df_lag = pd.DataFrame(df['Language'])
df_lag

                 Language
0                Japanese
1                 English
2                 English
3                  Others
4                 English
...                   ...
26288  English/Vietnamese
26289  English/Vietnamese
26290             English
26291             English
26292             English

[26293 rows x 1 columns]

In [12]:
# Extract individual words from combined language strings and count occurrences
lag_counts = Counter()
for lang in df['Language']:
    words = lang.split('/')
    unique_words = set(words)  # Keep only unique words in the language string
    lag_counts.update(unique_words)
    
# Create a DataFrame from the word counts
lag_counts_df = pd.DataFrame(lag_counts.items(), columns=['laguage', 'Frequency'])
lag_counts_df

             laguage  Frequency
0           Japanese        174
1            English      23414
2             Others       2195
3   Chinese-Mandarin       1278
4              Khmer        783
5             Korean         96
6  Chinese-Cantonese         62
7               Thai         99
8             French         50
9         Vietnamese         33

In [13]:
df.to_csv('dataset.csv', index=False)

### Visulization

# Get the HTML content of the app
app_html = app._generate_scripts_html()
# Save the HTML content to a file
with open('dashboard.html', 'w') as file:
    file.write(app_html)

We use Potly Dash to create 3 container

In [14]:
# set up the dash app
app = Dash(__name__)

# Set up style
title_style = {'color':'#ffffff', 'font-weight': 'bold',
               'font-family': "Fira Sans, sans-serif",'fontSize': '20px',
               'margin-top':'20px','margin-bottom': '20px'}
graph_dropdown_style = {'background-color':'#ffffff',
        'width': '100%',
        'color': '#0037FF',
        'text-align': 'None',
        'font-family': "Fira Sans, sans-serif",
        'font-size': '14px',
        'width': "18rem",
        'padding':'None',
        'margin':'None',
        'margin-top':'10px',
        'margin-bottom': '2px',
        'border': '3px #f7e99a',
        'border-radius': '2px',
        'background-image': 'None',
        #'box-shadow': '2px 2px 5px #999999',
        'box-shadow': 'rgba(0, 0, 0, 0.02) 0px 1px 3px 0px, rgba(27, 31, 35, 0.15) 0px 0px 0px 1px',
        'cursor': 'True',
        'font-style': 'None',
        'font-weight': 'normal'}
dropdown_style = {'background-color':'#12284C',
                                     'width': '100%',
                                     'color': '#0b0854',
                                     'text-align': 'None',
                                     'font-family': "Fira Sans, sans-serif",
                                     'font-size': '14px',
                                     'padding':'None',
                                     'margin':'None',
                                     'margin-top':'10px',
                                     'margin-bottom': '10px',
                                     'border': '3px lightblue',
                                     'border-radius': '10px',
                                     'background-image': 'None',
                                     #'box-shadow': '2px 2px 5px #999999',
                                     'cursor': 'True',
                                     'font-style': 'None',
                                     'font-weight': 'normal'}
checklist_style = {'background-color':'#12284C',
                                     'width': '100',
                                     'display': 'flex',
                                     'flex-direction': 'column',
                                     'color': '#CCCCCC',
                                     'font-family': "Fira Sans, sans-serif",
                                     'font-size': '14px',
                                     'margin-left': '20px',
                                     'margin-bottom': '10px',
                                     'margin-top':'10px',
                                     'font-weight':'550',
                                     'border': '3px #f7e99a',
                                     'border-radius': '10px'}
                                     #'box-shadow': '2px 2px 5px #999999'}
card_style = { "width": "18rem",
            "backgroundColor": "#ffffff",  # Background color
            "color": "#12284C",  # Text color
            #"border": "2px solid #007bff",  # Border with blue color
            "borderRadius": "20px",  # Rounded corners
            "boxShadow": "0 5px 10px rgba(0, 0, 0, 0.1)",  # Shadow effect
            "padding": "10px",  # Spacing inside the card},
            "verticalAlign": "center",  # Align cards at the top
            "fontSize": "14px",  # Font size of the card text
            "textAlign": "center",  # Center-align the card text
            "font-family": "Fira Sans, sans-serif",
            "height": "100px", } # Set the height of the card to 200 pixels


# Convert 'MonthYear' column to datetime type
df['MonthYear'] = pd.to_datetime(df['MonthYear'])
num_positions = len(df['Position'])
formatted_num_positions = "{:,}".format(num_positions)
num_hiring = sum(df['Hiring'])
formatted_num_hiring = "{:,}".format(num_hiring)

# Create a card to display the number of positions
card_position = dbc.Card(
        dbc.CardBody(
            [
                html.H4("Total Positions", className="card-title"),
                html.H1(formatted_num_positions, className="card-text"),
            ]
        ),

    color="#b2e6c6",
    inverse=True,
    style=card_style
)

card_hiring = dbc.Card(
    [
        dbc.CardBody(
            [
                html.H4("Total of Hiring", className="card-title"),
                html.H1(formatted_num_hiring, className="card-text"),
            ]
        )
    ],
    color="primary",
    inverse=True,
    style=card_style
)

card_categories = dbc.Card(
    [
        dbc.CardBody(
            [
                html.H4("Total Job Category", className="card-title"),
                html.H1(len(df['Job_Category'].unique()), className="card-text"),
            ]
        )
    ],
    color="primary",
    inverse=True,
    style=card_style
)

card_industry = dbc.Card(
    [
        dbc.CardBody(
            [
                html.H4("Total Industry", className="card-title"),
                html.H1(len(df['Industry'].unique()), className="card-text"),
            ]
        )
    ],
    color="primary",
    inverse=True,
    style=card_style
)

# Set up app layout
app.layout = html.Div(
    className = "container",
    style = {'display': 'flex', 'flex-direction': 'column','justify-content': 'space-between','background-color': '#12284C'},
    children = [
        html.Div(
            className = "header",
            style = {'flex':'0','padding': '0px'},
            children = [
                # html.Img(
                #     src= 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgJVILdD1h8PlbdJ_61yXjth8_8ATpkDmnZb1UqXuw&s',  # Replace with actual path
                #     style={'height': '500px', 'width':'00px'}  # Adjust the height as needed
                # ),​​​​​​
                html.H1('Cambodia Job Visualization', 
                        style={'text-align': 'center','color':'#FF4438',
                               'font-family': "Fira Sans, sans-serif",
                                'fontSize': '50px',
                                }),
            ]
        ),
        
        html.Div(
            className = "content",
            style = {'display': 'flex', 'flex-direction': 'row'},
            children = [
                html.Div(
                    className = "filters",
                    style = {'flex':'0.5','padding': '10px','justify-content':'flex-start','width':'100','background-color': '#12284C'},
                    children = [
                        html.Label(children = ['Job Category'], style = title_style),
                        dcc.Dropdown(
                            id = 'job-category-dropdown',
                            options = [{'label': category, 'value': category} for category in df['Job_Category'].unique()],
                            value = [],
                            multi = True,
                            searchable = True,
                            clearable = True,
                            placeholder = "Select job category",
                            style = dropdown_style
                        ),
                        html.Label(children = ['Industry'], style = title_style),
                        dcc.Dropdown(
                            id = 'industry-dropdown',
                            options = [{'label': industry, 'value': industry} for industry in df['Industry'].unique()],
                            value = [],
                            multi = True,
                            searchable = True,
                            clearable = True,
                            placeholder = "Select industry",
                            style = dropdown_style
                        ),
                        html.Label(children = ['Qualification'], style = title_style),
                        dcc.Dropdown(
                            id = 'qualification-dropdown',
                            options = [{'label': qualification, 'value': qualification} for qualification in df['Qualification'].unique()],
                            value = [],
                            multi = True,
                            searchable = True,
                            clearable = True,
                            placeholder = "Select qualification",
                            style = dropdown_style
                        ),
                        html.Label(children = ['Language'], style = title_style),
                        dcc.Dropdown(
                            id = 'language-dropdown',
                            options = [{'label': language, 'value': language} for language in df['Language'].unique()],
                            value = [],
                            multi = True,
                            searchable = True,
                            clearable = True,
                            placeholder = "Select language",
                            style = dropdown_style
                        ),
                        html.Label(children = ['Gender'], style = title_style),
                        dcc.Checklist(
                            id = 'gender-checkboxes',
                            options = [{'label': gender, 'value': gender} for gender in df['Gender'].unique()],
                            value = [],
                            inline = True,
                            style = checklist_style,
                            labelStyle={'padding': '5px'}
                        ),
                        html.Label(children = ['Job Type'], style = title_style),
                        dcc.Checklist(
                            id = 'job-type-checkboxes',
                            options = [{'label': job_type, 'value': job_type} for job_type in df['Job_Type'].unique()],
                            value = [],
                            inline = False,
                            style = checklist_style,
                            labelStyle={'padding': '5px'}
                        ),
                        html.Label(children = ['Position Level'], style = title_style),
                        dcc.Checklist(
                            id = 'position-level-checkboxes',
                            options = [{'label': position_level, 'value': position_level} for position_level in df['Position_Level'].unique()],
                            value = [],
                            inline = False,
                            style = checklist_style,
                            labelStyle={'padding': '5px'}
                        ),
                    ],
                ),
                
                html.Div(
                    className = "figure",
                    style = {'flex': '2','padding': '10px',
                             'justify-content': 'flex-end',
                             'width':'500',
                             'background-color': '#CCCCCC'},
                    children = [
                    html.Div(
                        [
                            card_position,
                            card_hiring,

                        ],
                        style={"display": "flex",
                               "justify-content": "space-around",
                               "margin": "20px"},
                    ),  

                    #dcc.Graph(id = "pie-graph"),
                    #html.Label(children = ['Select Total Number of Hirng base on Y-axis Variable: '], style = title_style),
                    dcc.Dropdown(
                        id="y-axis-dropdown",
                        options=[
                            {"label": html.Span(['Total Number of Hiring by Gender']),
                                                #style={'color': '#000000'}),
                                                "value": "Gender",
                                                "search": "Total Number of Hiring by Gender"},
                            {"label": html.Span(['Total Number of Hiring by Job Type']),
                                                #style={'color': '#000000'}),
                                                "value": "Job_Type",
                                                "search": "Total Number of Hiring by Job Type"},
                            {"label": html.Span(['Total Number of Hiring by Position Level']),
                                                #style={'color': '#000000'}),
                                                "value": "Position_Level",
                                                "search": "Total Number of Hiring by Position Level"},
                            {"label": html.Span(['Total Number of Hiring by Job Category']),
                                                #style={'color': '#000000'}),
                                                "value": "Job_Category",
                                                "search": "Total Number of Hiring by Job Category"},
                            {"label": html.Span(['Total Number of Hiring by Industry']),
                                                #style={'color': '#000000'}),
                                                "value": "Industry",
                                                "search": "Total Number of Hiring by Industry"},
                            {"label": html.Span(['Total Number of Hiring by Qualification']),
                                                #style={'color': '#000000'}),
                                                "value": "Qualification",
                                                "search": "Total Number of Hiring by Qualification"},
                        ],
                        value = "Gender",
                        placeholder = "Select here to see more",
                        style = graph_dropdown_style
                    ),
                    
                    dcc.Graph(id = "bar-graph"),
                    #dcc.Graph(id="word-cloud-lag", figure={}),
                    #dcc.Graph(id="word-cloud-loc", figure={}),
                    

                    dcc.Dropdown(
                    id='word-cloud-selector',
                    options=[
                        {"label": html.Span(['Frequency of language needed']),
                                            #style={'color': '#000000'}),
                                            "value": "cloud1",
                                            "search": "Frequency of language needed"},
                        {"label": html.Span(['Frequency of location needed']),
                                            #style={'color': '#000000'}),
                                            "value": "cloud2",
                                            "search": "Frequency of location needed"},
                        {"label": html.Span(['Frequency of Job title needed']),
                                            #style={'color': '#000000'}),
                                            "value": "cloud3",
                                            "search": "Frequency of Job title needed"},
                    ],
                    value= "cloud1", # Default value 
                    placeholder = "Select here to see more",
                    style = graph_dropdown_style
                    ),
                    dcc.Graph(id='word-cloud-output',figure={}),

                    # Nak
                    dcc.Dropdown(
                        id='salary-y-axis-dropdown',
                        options=[
                            {"label": html.Span(['Average Salary by Job Type']),
                                                "value": "Job_Type",
                                                "search": "Average Salary by Job Type"},
                            {"label": html.Span(['Average Salary by Position Level']),
                                                "value": "Position_Level",
                                                "search": "Average Salary by Position Level"},
                            {"label": html.Span(['Average Salary by Job Category']),
                                                "value": "Job_Category",
                                                "search": "Average Salary by Job Category"},
                            {"label": html.Span(['Average Salary by Industry']),
                                                "value": "Industry",
                                                "search": "Average Salary by Industry"},
                            {"label": html.Span(['Average Salary by Qualification']),
                                                "value": "Qualification",
                                                "search": "Average Salary by Qualification"},
                        ],
                        value= "Job_Type", # Default value 
                        placeholder = "Select here to see more",
                        style = graph_dropdown_style
                    ),
                    dcc.Graph(id='salary-graph',figure={}),


                    html.Label(children = ['Year Experience'], 
                                style = {'color':'#12284C', 'font-weight': 'bold',
                                        'font-family': "Fira Sans, sans-serif",'fontSize': '20px',
                                        'margin-top':'10px','margin-bottom': '10px'}),
                    
                    dcc.RangeSlider(
                        id='range-slider',
                        min=df['Year_Experience'].min(),
                        max=df['Year_Experience'].max(),
                        step=2,
                        marks={str(year): str(year) for year in range(df['Year_Experience'].min(),df['Year_Experience'].max()+1,2)},
                        value=[df['Year_Experience'].min(), df['Year_Experience'].max()],
                        vertical=False,
                        disabled=False,
                        dots=True,
                        included=True,
                        pushable=True,
                        tooltip={'placement': 'bottom'},
                        updatemode='mouseup',
                        # Adjust the margin-top value to control the spacing
                    ),
                
                    ],
                ),
             
                html.Div(
                    className = "figure",
                    style = {'flex': '2', 'padding': '10px','justify-content': 'flex-end','width':'500','background-color': '#CCCCCC'},
                    children = [
                                            
                    html.Div(
                        [
                            card_categories,
                            card_industry,
                        ],
                        style={"display": "flex", "justify-content": "space-around", "margin": "20px"},
                    ), 
                        
                    #dcc.Graph(id = "line-graph"),
                    #dcc.Graph(id = "scatter-graph"),
                    dcc.Dropdown(
                    id='graph-selector',
                    options=[
                            {"label": html.Span(['Number of hiring each month']),
                                                #style={'color': '#000000'}),
                                                "value": "line",
                                                "search": "Number of hiring each month"},
                            {"label": html.Span(['Number of hiring by average age']),
                                                #style={'color': '#000000'}),
                                                "value": "scatter",
                                                "search": "Number of hiring by average age"},
                    ],
                    value='line', # Default value 
                    placeholder = "Select here to see more",
                    style = graph_dropdown_style
                    ),
                    dcc.Graph(id='graph-output'),
                
                
                    dcc.Dropdown(
                        id='top-n-dropdown',
                        options = [{'label': f'Top {i}', 'value': i} for i in range(5, 101, 5)],  # Options from 1 to 10    
                        value= 5,  # Default value
                        placeholder="Select Top N",
                        style = graph_dropdown_style
                    ),
                    dcc.Graph(id = "treemap",figure={}),

                    # Nak
                    dcc.Dropdown(
                        # id='location-dropdown',
                        # # options = [{'label': f'Top {i}', 'value': i} for i in range(5, 101, 5)],  # Options from 1 to 10    
                        # # value= 5,  # Default value
                        placeholder="Select",
                        style = graph_dropdown_style
                    ),

                    dcc.Graph(id = "location-graph",figure={}),
                
                    ],
                ),
            ],
        ),
    ],
)

# Connect the Plotly graphs with Dash Components
@app.callback(
    #Output("line-graph", "figure"),
    #Output("scatter-graph", "figure"),
    #Output("pie-graph", "figure"),
    Output("graph-output", "figure"),
    Output("bar-graph", "figure"),
    Output("treemap", "figure"),
    Output("word-cloud-output", "figure"),
    Output("salary-graph", "figure"),
    Output("location-graph", "figure"),
    
    #Output("word-cloud-lag", "figure"),
    #Output("word-cloud-loc", "figure"),
    Input("range-slider", "value"),
    Input("job-category-dropdown", "value"),
    Input("industry-dropdown", "value"),
    Input("qualification-dropdown", "value"),
    Input("language-dropdown", "value"),
    Input("gender-checkboxes", "value"),
    Input("job-type-checkboxes", "value"),
    Input("position-level-checkboxes", "value"),
    Input("y-axis-dropdown", "value"), 
    Input("graph-selector", "value"),
    Input("top-n-dropdown", "value"),
    Input("word-cloud-selector", "value"),

    Input("salary-y-axis-dropdown", "value")
    # Input("location-y-axis-dropdown", "value")
)

# make graph update
def update_charts(slider_range, job_categories, industry, qualifications, language, gender, job_types, position_levels, y_axis_variable,selected_graph,top_n, graph_wordcloud, salary_y_axis_variable):
    low, high = slider_range

    # Apply filters for Year Experience, Job Category, Qualification, Language, Job Type, Position Level
    mask = (
        (df['Year_Experience'] > low) & 
        (df['Year_Experience'] < high) &
        (df['Job_Category'].isin(job_categories) if job_categories else True) &
        (df['Industry'].isin(industry) if industry else True) &
        (df['Qualification'].isin(qualifications) if qualifications else True) &
        (df['Language'].isin(language) if language else True) &
        (df['Gender'].isin(gender) if gender else True) &
        (df['Job_Type'].isin(job_types) if job_types else True) &
        (df['Position_Level'].isin(position_levels) if position_levels else True)
    )


    # # Count Numer of Gender
    # grouped_df_pie = df[mask].groupby('Gender').size().reset_index(name='Count')

    # pie_fig = px.pie(
    #     grouped_df_pie, values='Count', names='Gender'
        
    # )

    # pie_fig.update_layout(
    #     height=500,
    #     #width=300,
    #     margin=dict(l=40, r=40, t=50, b=10),
    #     title=dict(text='Gender Distribution', x=0.5),
    #     legend=dict(orientation="h",yanchor="bottom",xanchor="center",x=0.5) 
    # )
    
    # bar graph for total of hiring
    # Create the figure layout

    bar_fig = go.Figure()
    # Number of hiring by gender
    grouped_df_gender = df[mask].groupby(['Gender'])['Hiring'].sum().reset_index()
    grouped_df_gender = grouped_df_gender.sort_values('Hiring', ascending=True)

    # Number of hiring by Job Type
    grouped_df_jobtype = df[mask].groupby(['Job_Type'])['Hiring'].sum().reset_index()
    grouped_df_jobtype = grouped_df_jobtype.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Position Level
    grouped_df_positionlevel = df[mask].groupby(['Position_Level'])['Hiring'].sum().reset_index()
    grouped_df_positionlevel = grouped_df_positionlevel.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Job Category
    grouped_df_jobcategory = df[mask].groupby(['Job_Category'])['Hiring'].sum().reset_index()
    grouped_df_jobcategory = grouped_df_jobcategory.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Industry
    grouped_df_industry = df[mask].groupby(['Industry'])['Hiring'].sum().reset_index()
    grouped_df_industry = grouped_df_industry.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Qualification
    grouped_df_qualification = df[mask].groupby(['Qualification'])['Hiring'].sum().reset_index()
    grouped_df_qualification = grouped_df_qualification.sort_values('Hiring', ascending=True)

    # Set the Y-axis variable based on the dropdown value
    if y_axis_variable == 'Gender':
        bar_data = grouped_df_gender
        title = "<b>Total Number of Hiring by Gender<b>"
        x_variable = "Hiring"
        y_variable = "Gender"
        xaxis_type = 'linear'
        color = '#00aeff'
    elif y_axis_variable == 'Job_Type':
        bar_data = grouped_df_jobtype
        title = "<b>Total Number of Hiring by Job Type<b>"
        x_variable = "Hiring"
        y_variable = "Job_Type"
        color = '#37bcb6'
    elif y_axis_variable == 'Position_Level':
        bar_data = grouped_df_positionlevel
        title = "<b>Total Number of Hiring by Position Level<b>"
        x_variable = "Hiring"
        y_variable = "Position_Level"
        color = '#a7c5f9'
    elif y_axis_variable == 'Job_Category':
        bar_data = grouped_df_jobcategory
        title = "<b>Total Number of Hiring by Job Category<b>"
        x_variable = "Hiring"
        y_variable = "Job_Category"
        color = '#7582e4'
    elif y_axis_variable == 'Industry':
        bar_data = grouped_df_industry
        title = "<b>Total Number of Hiring by Industry<b>"
        x_variable = "Hiring"
        y_variable = "Industry"
        color = '#1d79cb'
    else:
        bar_data = grouped_df_qualification
        title = "<b>Total Number of Hiring by Qualification<b>"
        x_variable = "Hiring"
        y_variable = "Qualification"
        color = '#ecc17b'
    xaxis_type = 'log'
    orientation =   'h'
   
    # Create the bar trace
    bar_fig.add_trace(go.Bar(
        x = bar_data[x_variable],
        y = bar_data[y_variable],
        name = title,
        marker_color=color,
        orientation = orientation
    ))

    # Update the figure layout
    bar_fig.update_layout(
        height=500,
        margin=dict(l=40, r=40, t=50, b=30),
        title=title,
        xaxis_type=xaxis_type,
        xaxis_title=x_variable,
        yaxis_title="Total Hiring",
        title_font_family = "Fira Sans, sans-serif",
        title_x = 0.5,
        font_color = "blue",
        title_font = dict(size=20, family="Fira Sans, sans-serif", color='#674ea7'),
        plot_bgcolor='#ffffff',# Set the background color of the plot area
        paper_bgcolor='#ffffff',  # Set the background color outside the plot
        xaxis_showgrid=False,  # Remove x-axis gridlines
        yaxis_showgrid=False,  # Remove y-axis gridlines

    )

    # Nak
    salary_fig = go.Figure()
    # Number of hiring by gender
    grouped_df_gender = df[mask].groupby(['Gender'])['Hiring'].sum().reset_index()
    grouped_df_gender = grouped_df_gender.sort_values('Hiring', ascending=True)

    # Number of hiring by Job Type
    grouped_df_jobtype = df[mask].groupby(['Job_Type'])['Hiring'].sum().reset_index()
    grouped_df_jobtype = grouped_df_jobtype.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Position Level
    grouped_df_positionlevel = df[mask].groupby(['Position_Level'])['Hiring'].sum().reset_index()
    grouped_df_positionlevel = grouped_df_positionlevel.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Job Category
    grouped_df_jobcategory = df[mask].groupby(['Job_Category'])['Hiring'].sum().reset_index()
    grouped_df_jobcategory = grouped_df_jobcategory.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Industry
    grouped_df_industry = df[mask].groupby(['Industry'])['Hiring'].sum().reset_index()
    grouped_df_industry = grouped_df_industry.sort_values('Hiring', ascending=True)
    
    # Number of hiring by Qualification
    grouped_df_qualification = df[mask].groupby(['Qualification'])['Hiring'].sum().reset_index()
    grouped_df_qualification = grouped_df_qualification.sort_values('Hiring', ascending=True)

    # Set the Y-axis variable based on the dropdown value
    if salary_y_axis_variable == 'Job_Type':
        bar_data = grouped_df_jobtype
        title = "<b>Average Salary by Job Type<b>"
        x_variable = "Hiring"
        y_variable = "Job_Type"
        color = '#37bcb6'
    elif salary_y_axis_variable == 'Position_Level':
        bar_data = grouped_df_positionlevel
        title = "<b>Average Salary by Position Level<b>"
        x_variable = "Hiring"
        y_variable = "Position_Level"
        color = '#a7c5f9'
    elif salary_y_axis_variable == 'Job_Category':
        bar_data = grouped_df_jobcategory
        title = "<b>Average Salary by Job Category<b>"
        x_variable = "Hiring"
        y_variable = "Job_Category"
        color = '#7582e4'
    elif salary_y_axis_variable == 'Industry':
        bar_data = grouped_df_industry
        title = "<b>Average Salary by Industry<b>"
        x_variable = "Hiring"
        y_variable = "Industry"
        color = '#1d79cb'
    else:
        bar_data = grouped_df_qualification
        title = "<b>Average Salary by Qualification<b>"
        x_variable = "Hiring"
        y_variable = "Qualification"
        color = '#ecc17b'
    xaxis_type = 'log'
    orientation =   'h'
   
    # Create the bar trace
    salary_fig.add_trace(go.Bar(
        x = bar_data[x_variable],
        y = bar_data[y_variable],
        name = title,
        marker_color=color,
        orientation = orientation
    ))

    # Update the figure layout
    salary_fig.update_layout(
        height=500,
        margin=dict(l=40, r=40, t=50, b=30),
        title=title,
        xaxis_type=xaxis_type,
        xaxis_title=x_variable,
        yaxis_title="Total Hiring",
        title_font_family = "Fira Sans, sans-serif",
        title_x = 0.5,
        font_color = "blue",
        title_font = dict(size=20, family="Fira Sans, sans-serif", color='#674ea7'),
        plot_bgcolor='#ffffff',# Set the background color of the plot area
        paper_bgcolor='#ffffff',  # Set the background color outside the plot
        xaxis_showgrid=False,  # Remove x-axis gridlines
        yaxis_showgrid=False,  # Remove y-axis gridlines

    )

    # Nak
    d1 = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')

    location_fig = go.Figure(data=go.Choropleth(
        locations = d1['CODE'],
        z = d1['GDP (BILLIONS)'],
        text = d1['COUNTRY'],
        colorscale = 'Blues',
        autocolorscale=False,
        reversescale=True,
        marker_line_color='darkgray',
        marker_line_width=0.5,
        colorbar_tickprefix = '$',
        colorbar_title = 'GDP<br>Billions US$',
    ))

    location_fig.update_layout(
        title_text='2014 Global GDP',
        geo=dict(
            showframe=False,
            showcoastlines=False,
            projection_type='equirectangular'
        )
    )
        
    
    
    
    # Set up wordcloud for lang, location, job title
    cloud_fig = go.Figure()

    if graph_wordcloud == 'cloud1':
        # Generate the word cloud image for language
        lag_counts = Counter()
        for lang in df[mask]['Language']:
            words = lang.split('/')
            unique_words = set(words)  # Keep only unique words in the language string
            lag_counts.update(unique_words)

        # Create a DataFrame from the word counts
        lag_counts_df = pd.DataFrame(lag_counts.items(), columns=['language', 'Frequency'])

        # Generate a word cloud from the filtered languages
        wordcloud = WordCloud(width=1200, height=600, 
                              background_color='#e9f3fb',
                              #font_path='Calibri',
                              font_step=2).generate_from_frequencies(lag_counts_df.set_index('language')['Frequency'])

        # Save the word cloud image to a BytesIO object
        img_buffer = BytesIO()
        wordcloud.to_image().save(img_buffer, format="PNG")

        # Encode the image data as base64
        img_data = base64.b64encode(img_buffer.getvalue())

        # Create a Plotly figure with an image trace for language
        word_cloud_lag = {
            "data": [
                {
                    "type": "image",
                    "source": f"data:image/png;base64,{img_data.decode()}",
                    "x": 2,
                    "y": 2,
                    "xref": "paper",
                    "yref": "paper",
                    "sizex": 100,
                    "sizey": 10,
                    "sizing": "stretch",
                }
            ],
            "layout": {
                "xaxis": {"visible": False},
                "yaxis": {"visible": False},
                "title": {
                    "text": "<b>Frequency of Languages Needed<b>",
                    "x": 0.5,
                    "font": {"color": "#674ea7","family": "Fira Sans, sans-serif","size":20},
                },
                "plot_bgcolor": "#ffffff",  # Set the background color of the plot area
                "paper_bgcolor": "#ffffff",  # Set the background color outside the plot
            },
        }
        cloud_fig = word_cloud_lag

    elif graph_wordcloud == 'cloud2':
        # Generate the word cloud image for location
        lag_counts = Counter()
        for loc in df[mask]['Location']:
            words = loc.split('/')
            unique_words = set(words)  # Keep only unique words in the location string
            lag_counts.update(unique_words)

        # Create a DataFrame from the word counts
        lag_counts_df = pd.DataFrame(lag_counts.items(), columns=['location', 'Frequency'])

        # Generate a word cloud from the filtered locations
        wordcloud = WordCloud(width=1200, height=600, font_step=2, background_color='#e9f3fb').generate_from_frequencies(lag_counts_df.set_index('location')['Frequency'])

        # Save the word cloud image to a BytesIO object
        img_buffer = BytesIO()
        wordcloud.to_image().save(img_buffer, format="PNG")

        # Encode the image data as base64
        img_data = base64.b64encode(img_buffer.getvalue())

        # Create a Plotly figure with an image trace for location
        word_cloud_loc = {
            "data": [
                {
                    "type": "image",
                    "source": f"data:image/png;base64,{img_data.decode()}",
                    "x": 2,
                    "y": 2,
                    "xref": "paper",
                    "yref": "paper",
                    "sizex": 100,
                    "sizey": 10,
                    "sizing": "stretch",
                }
            ],
            "layout": {
                "xaxis": {"visible": False},
                "yaxis": {"visible": False},
                "title": {
                    "text": "<b>Frequency of Locations Needed<b>",
                    "x": 0.5,
                    "font": {"color": "#674ea7","family": "Fira Sans, sans-serif","size":20},
                },
                "plot_bgcolor": "#ffffff",  # Set the background color of the plot area
                "paper_bgcolor": "#ffffff",  # Set the background color outside the plot
            },
        }
        cloud_fig = word_cloud_loc
        
    else :
        # Generate the word cloud image for location
        job_title_counts = Counter()
        for loc in df[mask]['Job_Title']:
            words = loc.split(',')
            unique_words = set([word.strip().lower() for word in words])   # Convert to lowercase and keep only unique words
            job_title_counts.update(unique_words)

        # Create a DataFrame from the word counts
        job_title_counts_df = pd.DataFrame(job_title_counts.items(), columns=['job_title', 'Frequency'])

        # Generate a word cloud from the filtered locations
        wordcloud = WordCloud(width=1200, height=600, font_step=2, background_color='#e9f3fb').generate_from_frequencies(job_title_counts_df.set_index('job_title')['Frequency'])

        # Save the word cloud image to a BytesIO object
        img_buffer = BytesIO()
        wordcloud.to_image().save(img_buffer, format="PNG")

        # Encode the image data as base64
        img_data = base64.b64encode(img_buffer.getvalue())

        # Create a Plotly figure with an image trace for location
        word_cloud_loc = {
            "data": [
                {
                    "type": "image",
                    "source": f"data:image/png;base64,{img_data.decode()}",
                    "x": 2,
                    "y": 2,
                    "xref": "paper",
                    "yref": "paper",
                    "sizex": 100,
                    "sizey": 10,
                    "sizing": "stretch",
                }
            ],
            "layout": {
                "xaxis": {"visible": False},
                "yaxis": {"visible": False},
                "title": {
                    "text": "<b>Frequency of job title Needed<b>",
                    "x": 0.5,
                    "font": {"color": "#674ea7","family": "Fira Sans, sans-serif","size":20},
                },
                "plot_bgcolor": "#ffffff",  # Set the background color of the plot area
                "paper_bgcolor": "#ffffff",  # Set the background color outside the plot
            },
        }
        cloud_fig = word_cloud_loc
    
    # line graph and scatter plot for total number of hiring
    graph_fig = go.Figure()
        
    if selected_graph =='line':
        # Group by MonthYear and calculate the sum of hiring
        grouped_df_line = df[mask].groupby(['MonthYear'])['Hiring'].sum().reset_index()
        
        # Sort the DataFrame by MonthYear
        grouped_df_line = grouped_df_line.sort_values('MonthYear')
        graph_fig  = px.line(
            grouped_df_line, x="MonthYear", y="Hiring",
            color_discrete_sequence=['#ee9a00'],
            markers=False,
            labels={"MonthYear": "Month-Year", "Hiring": "Total Hiring"},
            title="<b>Total Number of Hiring Each Month</b>",
                
        )
        
        graph_fig .update_layout(
            height = 500,
            #font_family = "Arial, sans-serif",
            title_font_family = "Fira Sans, sans-serif",
            title_x = 0.5,
            font_color = "blue",
            title_font = dict(size=20, family="Fira Sans, sans-serif", color='#674ea7'),
            legend_title_font_color = "black",
            margin=dict(l=50, r=50, t=50, b=50),
            plot_bgcolor='#ffffff',# Set the background color of the plot area
            paper_bgcolor='#ffffff',  # Set the background color outside the plot
            xaxis_showgrid=False,  # Remove x-axis gridlines
            yaxis_showgrid=False,  # Remove y-axis gridlinest
            
        )
    
    elif selected_graph == 'scatter':
        # Group by Average Age and calculate the sum of hiring
        grouped_df_scatter = df[mask].groupby(['Average_Age','Gender'])['Hiring'].sum().reset_index()
        
        
        graph_fig  = px.scatter(
            grouped_df_scatter, x="Hiring", y="Average_Age",
            color = "Gender", 
            size='Average_Age',
            #animation_frame="Average_Age",
            #animation_group="Gender",
            log_x=True, size_max=20, range_y=[15,55],
            labels={"Average_Age": "Average Age", "Hiring": "Total Hiring"},
            title="<b>Total Hiring by Average Age<b>"
        )

        graph_fig.update_layout(
            height=500,
            margin=dict(l=50, r=50, t=50, b=50),
            title_font_family = "Fira Sans, sans-serif",
            title_x = 0.5,
            font_color = "blue",
            title_font = dict(size=20, family="Fira Sans, sans-serif", color='#674ea7'),
            legend_title_font_color = "black",
            legend=dict(orientation="h",yanchor="top",xanchor="center",x=0.5,y=-0.2),
            plot_bgcolor='#ffffff',# Set the background color of the plot area
            paper_bgcolor='#ffffff',  # Set the background color outside the plot
            xaxis_showgrid=False,  # Remove x-axis gridlines
            yaxis_showgrid=False,  # Remove y-axis gridlines
        )
        
    # Treemap job title frequency count
    # Job title frequency count
    job_title_counts = Counter()
    for title in df[mask]['Job_Title']:
        words = title.split(',')
        unique_words = set([word.strip().lower() for word in words])
        job_title_counts.update(unique_words)

    # Create a DataFrame from the word counts
    job_title_counts_df = pd.DataFrame(job_title_counts.items(), columns=['job_title', 'Frequency'])

    # Get the top N most common job titles
    top_job_titles = job_title_counts.most_common(top_n)

    # Prepare data for Plotly treemap
    labels = [title[0] for title in top_job_titles]
    values = [title[1] for title in top_job_titles]

    # Create a treemap figure using Plotly
    fig_treemap = go.Figure(go.Treemap(
        labels=labels,
        parents=[""] * len(labels),  # All labels are top-level categories
        values=values,
        text=values
    ))

    # Set layout for the treemap figure
    fig_treemap.update_layout(
        title="<b>Top {} Job Title Frequencies<b>".format(top_n),
        height=450,
        title_font_family="Fira Sans, sans-serif",
        title_x=0.5,
        font_color="red",
        title_font=dict(size=20, family="Fira Sans, sans-serif", color='#674ea7'),
        margin=dict(t=60, b=30, l=0, r=0),
        plot_bgcolor='#ffffff',  # Set the background color of the plot area
        paper_bgcolor='#ffffff',  # Set the background color outside the plot
    )
    
    

    return graph_fig, bar_fig, fig_treemap, cloud_fig, salary_fig, location_fig


if __name__ == '__main__':
    app.run(jupyter_mode="external",debug=True) # defualt hosting

Dash app running on http://127.0.0.1:8050/

In [15]:
# if __name__ == '__main__':
#     app.run(jupyter_mode="external",debug=True) # defualt hosting
#     #app.run(jupyter_server_url="http://172.23.32.100:8050")
#     #app.run_server(host='172.23.32.100', port='8050',debug=True)